### ISSUE TITLE
Bliss include path is not correct when bliss is already installed

### ISSUE THREAD

**Issue by hedtke** [scipopt/scip#117]
I want to update the conan recipe. In conan we install bliss as dependency. In [CMake](https://github.com/scipopt/scip/blob/master/CMakeLists.txt#L137), `find_package(Bliss` is used, but  then `Bliss_INCLUDE_DIRS` is unused, instead paths are constructed by hand. If bliss is installed externally, the include paths are wrong

**Comment by svigerske** [comment]
It has been changed to
```
find_package(Bliss CONFIG HINTS ${BLISS_DIR})
set(SYM_LIBRARIES Bliss::libbliss)
set(SYM_PIC_LIBRARIES Bliss::libbliss)
```
This should work with bliss from https://github.com/scipopt/bliss when build via cmake, since that should create a `BlissConfig.cmake` that provides `Bliss::libbliss`.

I don't really know how compatible that is with the bliss build in the conda packages, though. You seem to use `bliss::bliss` in your patch.
